#spring配置
#spring:
#  #数据源
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test_database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: XS
#    password: XS123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource

#配置多数据源
spring:
  datasource:
    #用户数据源配置
    user-source:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/user_database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: XS
      password: XS123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      #type: com.alibaba.druid.pool.DruidDataSource
    #测试数据源配置
    test-source:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_database?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: tag
      password: XS123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      #type: com.alibaba.druid.pool.DruidDataSource

#mybatis配置
mybatis:
  configuration:
    #开启驼峰命名：javabean->uId database->u_id
    map-underscore-to-camel-case: true
    #开启mybatis控制台日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #实体类别名扫描
  type-aliases-package: com.tag.springbootmybatis.beans
#在多数据源的情况下会使用多个mybatis的@configuration配置类，
#他们相当于mybatis-config.xml,并且他们内部会有一些默认的mybatis配置，
#优先级高于普通配置文件，所以配置文件中的mybatis配置将不会生效，所以需要导入配置文件到配置类当中

#分页插件
pagehelper:
  #数据库不同分页原理也不同
  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  pageSizeZero: true
#  params: count=countSql